Mesd\UserBundle\Entity\FilterJoin:
    type: entity
    table: mesd_user_filter_join
    repositoryClass: Mesd\UserBundle\Repository\FilterJoinRepository

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        value:
            type: integer
            column: value
            nullable: false
        description:
            type: text
            column: description
            nullable: false

    manyToMany:
        filterCell:
            targetEntity: FilterCell
            mappedBy: filterJoin

        filterAssociation:
            targetEntity: FilterAssociation
            inversedBy: filterJoin
            cascade: {  }
            joinTable:
                name: filter_join__filter_association
                joinColumns:
                    filter_join_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    filter_association_id:
                        referencedColumnName: id
