Mesd\UserBundle\Entity\FilterCell:
    type: entity
    table: mesd_user_filter_cell
    repositoryClass: Mesd\UserBundle\Repository\FilterCellRepository

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        description:
            type: text
            column: description
            nullable: false
