Mesd\UserBundle\Entity\Filter:
    type: entity
    table: mesd_user_filter
    repositoryClass: Mesd\UserBundle\Repository\FilterRepository

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        description:
            type: text
            column: description
            nullable: false

    manyToMany:
        filterRow:
            targetEntity: FilterRow
            inversedBy: filter
            cascade: {  }
            joinTable:
                name: filter__filter_row
                joinColumns:
                    filter_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    filter_row_id:
                        referencedColumnName: id