Mesd\UserBundle\Entity\FilterAssociation:
    type: entity
    table: mesd_user_filter_association
    repositoryClass: Mesd\UserBundle\Repository\FilterAssociationRepository

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        name:
            type: string
            column: name
            nullable: false
        trail:
            type: text
            column: trail
            nullable: false
