Mesd\UserBundle\Entity\FilterRow:
    type: entity
    table: mesd_user_filter_row
    repositoryClass: Mesd\UserBundle\Repository\FilterRowRepository

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        description:
            type: text
            column: description
            nullable: false
