Mesd\UserBundle\Entity\FilterRow:
    type: entity
    table: mesd_user_filter_row
    repositoryClass: Mesd\UserBundle\Repository\FilterRowRepository

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        description:
            type: text
            column: description
            nullable: false

    manyToMany:
        filter:
            targetEntity: Filter
            mappedBy: filterRow

        filterCell:
            targetEntity: FilterCell
            inversedBy: filterRow
            cascade: {  }
            joinTable:
                name: filter_row__filter_cell
                joinColumns:
                    filter_row_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    filter_cell_id:
                        referencedColumnName: id