Mesd\UserBundle\Entity\FilterCell:
    type: entity
    table: mesd_user_filter_cell
    repositoryClass: Mesd\UserBundle\Repository\FilterCellRepository

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        description:
            type: text
            column: description
            nullable: false

    manyToMany:
        filterRow:
            targetEntity: FilterRow
            mappedBy: filterCell

        filterJoin:
            targetEntity: FilterJoin
            inversedBy: filterCell
            cascade: {  }
            joinTable:
                name: filter_cell__filter_join
                joinColumns:
                    filter_cell_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    filter_join_id:
                        referencedColumnName: id