Mesd\UserBundle\Entity\FilterJoin:
    type: entity
    table: mesd_user_filter_join
    repositoryClass: Mesd\UserBundle\Repository\FilterJoinRepository

    fields:
        id:
            id: true
            type: integer
            nullable: false
            generator:
                strategy: AUTO
        value:
            type: integer
            column: value
            nullable: false
        description:
            type: text
            column: description
            nullable: false
