Mesd\UserBundle\Entity\Group:
  type: mappedSuperclass
  fields:
    name:
      type: string
      length: 255
      nullable: false
      unique: true
    description:
      type: text
      nullable: true