Mesd\UserBundle\Entity\Role:
    type: mappedSuperclass
    fields:
        name:
            type: string
            length: 255
            nullable: true
            unique: true
        description:
            type: text
            nullable: false