parameters:
    mesd_user.role_manager.class:   Mesd\UserBundle\Model\RoleManager
    mesd_user.role_hierarchy.class: Mesd\UserBundle\Model\RoleHierarchy

services:
    mesd_user.role_manager:
        class: %mesd_user.role_manager.class%
        arguments: [@doctrine, %mesd_user.role_class%]
    mesd_user.role_hierarchy:
        class: %mesd_user.role_hierarchy.class%
        arguments: [%security.role_hierarchy.roles%]