parameters:
    mesd_user.user_manager.class: Mesd\UserBundle\Model\UserManager

services:
    mesd_user.user_manager:
        class: %mesd_user.user_manager.class%
        arguments: [@doctrine, @security.encoder_factory, %mesd_user.user_class%, %mesd_user.role_class%]