<?php

namespace Mesd\UserBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    /**
     * Generates the configuration tree.
     *
     * @return TreeBuilder
     */
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('mesd_user')
            ->addDefaultsIfNotSet()
            ->children()
                ->scalarNode('user_class')
                    ->isRequired()
                    ->cannotBeEmpty()
                ->end()
                ->scalarNode('role_class')
                    ->isRequired()
                    ->cannotBeEmpty()
                ->end()
                ->scalarNode('group_class')
                ->end()
                ->arrayNode('login')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->enumNode('revisit_behavior')
                            ->values(array('logout', 'redirect', 'status'))
                            ->defaultValue('status')
                        ->end()
                        ->scalarNode('revisit_redirect_target')
                            ->defaultValue(null)
                        ->end()
                        ->scalarNode('template')
                            ->defaultValue('MesdUserBundle:security:login.html.twig')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('registration')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('approval_mail')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('approval_mail_from')
                            ->defaultValue('webmaster@example.com')
                        ->end()
                        ->scalarNode('approval_mail_subject')
                            ->defaultValue('Account Needs Approval')
                        ->end()
                        ->scalarNode('approval_mail_to')
                            ->defaultValue(null)
                        ->end()
                        ->booleanNode('approval_required')
                            ->defaultFalse()
                        ->end()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('link_text')
                            ->defaultValue('Create Account')
                        ->end()
                        ->booleanNode('mail_confirmation')
                            ->defaultFalse()
                        ->end()
                        ->scalarNode('mail_from')
                            ->defaultValue('webmaster@example.com')
                        ->end()
                        ->scalarNode('mail_subject')
                            ->defaultValue('Account Created')
                        ->end()
                        ->arrayNode('template')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('approve')
                                    ->defaultValue('MesdUserBundle:registration:approve.html.twig')
                                ->end()
                                ->scalarNode('approval_mail')
                                    ->defaultValue('MesdUserBundle:registration:approvalEmail.txt.twig')
                                ->end()
                                ->scalarNode('confirm')
                                    ->defaultValue('MesdUserBundle:registration:confirm.html.twig')
                                ->end()
                                ->scalarNode('confirm_mail')
                                    ->defaultValue('MesdUserBundle:registration:confirmEmail.txt.twig')
                                ->end()
                                ->scalarNode('register')
                                    ->defaultValue('MesdUserBundle:registration:register.html.twig')
                                ->end()
                                ->scalarNode('summary')
                                    ->defaultValue('MesdUserBundle:registration:summary.html.twig')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('reset')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                        ->end()
                        ->arrayNode('template')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->scalarNode('reset')
                                    ->defaultValue('MesdUserBundle:reset:reset.html.twig')
                                ->end()
                            ->end()
                        ->end()
                        ->scalarNode('link_text')
                            ->defaultValue('Reset Password')
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
