MesdUserBundle_filter_index:
    pattern: /
    defaults: { _controller: MesdUserBundle:Filter:index }
    methods:  [GET]

MesdUserBundle_filter_new:
    pattern: /new
    defaults: { _controller: MesdUserBundle:Filter:new }
    methods:  [GET]

MesdUserBundle_filter_solvent:
    pattern: /solvent
    defaults: { _controller: MesdUserBundle:Filter:solvent }
    methods:  [GET]

MesdUserBundle_filter_create:
    pattern: /create
    defaults: { _controller: MesdUserBundle:Filter:create }
    methods:  [POST]

MesdUserBundle_filter_show:
    pattern: /show/{id}
    defaults: { _controller: MesdUserBundle:Filter:show }
    methods:  [GET]
