MesdUserBundle_filter:
    pattern: /
    defaults: { _controller: MesdUserBundle:Filter:index }
    methods:  [GET]

MesdUserBundle_filter_allusers:
    pattern: /allusers
    defaults: { _controller: MesdUserBundle:Filter:allUsers }
    methods:  [GET]

MesdUserBundle_filter_create:
    pattern: /create
    defaults: { _controller: MesdUserBundle:Filter:create }
    methods:  [POST]

MesdUserBundle_filter_eachuser:
    pattern: /eachuser
    defaults: { _controller: MesdUserBundle:Filter:eachUser }
    methods:  [GET]

MesdUserBundle_filter_edit:
    pattern: /{id}/edit
    defaults: { _controller: MesdUserBundle:Filter:edit }
    methods:  [GET]

MesdUserBundle_filter_new:
    pattern: /new
    defaults: { _controller: MesdUserBundle:Filter:new }
    methods:  [GET]

MesdUserBundle_filter_show:
    pattern: /{id}/show
    defaults: { _controller: MesdUserBundle:Filter:show }
    methods:  [GET]

MesdUserBundle_filter_solvent:
    pattern: /solvent
    defaults: { _controller: MesdUserBundle:Filter:solvent }
    methods:  [GET]

MesdUserBundle_filter_update:
    pattern: /{id}/update
    defaults: { _controller: MesdUserBundle:Filter:update }
    methods:  [POST]

