MesdUserBundle_onefiltermanyusers:
    path:     /
    defaults: { _controller: "MesdUserBundle:OneFilterManyUsers:index" }

MesdUserBundle_onefiltermanyusers_edit:
    path:     /{id}/edit
    defaults: { _controller: "MesdUserBundle:OneFilterManyUsers:edit" }

MesdUserBundle_onefiltermanyusers_show:
    path:     /{id}/show
    defaults: { _controller: "MesdUserBundle:OneFilterManyUsers:show" }

MesdUserBundle_onefiltermanyusers_update:
    path:     /{id}/update
    defaults: { _controller: "MesdUserBundle:OneFilterManyUsers:update" }
    methods:  [POST, PUT]
