MesdUserBundle_oneusermanyfilters:
    path:     /
    defaults: { _controller: "MesdUserBundle:OneUserManyFilters:index" }

MesdUserBundle_oneusermanyfilters_edit:
    path:     /{id}/edit
    defaults: { _controller: "MesdUserBundle:OneUserManyFilters:edit" }

MesdUserBundle_oneusermanyfilters_show:
    path:     /{id}/show
    defaults: { _controller: "MesdUserBundle:OneUserManyFilters:show" }

MesdUserBundle_oneusermanyfilters_update:
    path:     /{id}/update
    defaults: { _controller: "MesdUserBundle:OneUserManyFilters:update" }
    methods:  [POST, PUT]
