MesdUserBundle_registration_new:
    pattern: /new
    defaults: { _controller: MesdUserBundle:Registration:new }

MesdUserBundle_registration_create:
    pattern: /create
    defaults: { _controller: MesdUserBundle:Registration:create }