MesdUserBundle_registration_new:
    pattern: /new
    defaults: { _controller: MesdUserBundle:Registration:new }

MesdUserBundle_registration_create:
    pattern: /create
    defaults: { _controller: MesdUserBundle:Registration:create }

MesdUserBundle_registration_confirm:
    pattern: /confirm/{token}
    defaults: { _controller: MesdUserBundle:Registration:confirm }