MesdUserBundle_reset_request:
    path: /request
    defaults: { _controller: MesdUserBundle:Reset:request }
    methods:  [GET]

MesdUserBundle_reset_send_email:
    path: /send-email
    defaults: { _controller: MesdUserBundle:Reset:sendEmail }
    methods:  [POST]

MesdUserBundle_reset_new_password:
    path: /new-password/{token}
    defaults: { _controller: MesdUserBundle:Reset:newPassword }
    methods:  [GET|POST]

MesdUserBundle_reset_success:
    path: /success
    defaults: { _controller: MesdUserBundle:Reset:success }
    methods:  [GET]