MesdUserBundle_login:
    path: /login
    defaults: { _controller: MesdUserBundle:Security:login }

MesdUserBundle_check:
    path: /login_check
    defaults: { _controller: MesdUserBundle:Security:check }
    methods:  [POST]

MesdUserBundle_logout:
    path: /logout
    defaults: { _controller: MesdUserBundle:Security:logout }