MesdUserBundle_user:
    path:     /
    defaults: { _controller: "MesdUserBundle:User:index" }

MesdUserBundle_user_show:
    path:     /{id}/show
    defaults: { _controller: "MesdUserBundle:User:show" }

MesdUserBundle_user_new:
    path:     /new
    defaults: { _controller: "MesdUserBundle:User:new" }

MesdUserBundle_user_create:
    path:     /create
    defaults: { _controller: "MesdUserBundle:User:create" }
    requirements: { methods: post }

MesdUserBundle_user_edit:
    path:     /{id}/edit
    defaults: { _controller: "MesdUserBundle:User:edit" }

MesdUserBundle_user_update:
    path:     /{id}/update
    defaults: { _controller: "MesdUserBundle:User:update" }
    requirements: { methods: post|put }

MesdUserBundle_user_delete:
    path:     /{id}/delete
    defaults: { _controller: "MesdUserBundle:User:delete" }
    requirements: { methods: post|delete }
